# server
server:
  port: 5505
  tomcat:
    max-threads: 50
    min-spare-threads: 20
  servlet:
    context-path: '/e-journal'
    session:
      timeout: 30m

# spring
spring:
  application:
    name: '@project.artifactId@'

  # datasource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: '@flyway.url@'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: '@flyway.user@'
    password: '@flyway.password@'
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      minimumIdle: 2
      transactionIsolation: TRANSACTION_READ_COMMITTED
      connectionTestQuery: SELECT version()

  # hibernate
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# logging
logging:
  file:
    max-history: 10
    max-size: 20MB
  level:
    root: INFO
    com.corelogic.mts.util.LoggingTraceRepository: DEBUG
    com.corelogic.mts: INFO
    org.hibernate: ERROR
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping: INFO
    liquibase: INFO

#Cors
cors:
  pathMapping: '/**'
  allowedOrigins: 'http://localhost:3000'
  allowedMethods: 'GET,POST,PUT,DELETE'